### ISSUE TITLE
「チーム的な事にあまり口を出さない利点」の記事が重複しているようです

### ISSUE THREAD

**Issue by 1s22s1** [karino2/karino2.github.io#243]
はじめまして。Message Passingがきっかけでブログを読ませて頂いています。差し出がましいとは、思うのですが「チーム的な事にあまり口を出さない利点」の記事が重複しているようです。

- https://karino2.github.io/2017/09/22/37.html
- https://karino2.github.io/2017/09/22/123456.html

以上、ご報告まででした。

**Comment by karino2** [comment]
おぉ、本当だ。どうもです。
